### ISSUE TITLE
Linux peer review

### ISSUE THREAD

**Issue by tt-le** [OpenLiberty/draft-guide-contract-testing#4] opened 2020-12-23 20:36 UTC
## Overall
- [ ] Experiencing the same image distortion outlined in https://github.com/OpenLiberty/draft-guide-contract-testing/issues/3.

## Implementing the pact test in the inventory service

- [ ] Navigate to the `start/inventory` directory to begin. -> Navigate to the `start` directory to begin. This is because `inventory/` is in the path when we ask the user to create files. It is a bit awkward to run `vim src/test/java/io/openliberty/guides/inventory/InventoryPactIT.java` whereas in the other guides you could copy the entire path to create a file in the correct location.
- [ ] `InventoryPactIT` doesn't have a hotspot, not sure if it should.

## Verifying the contract 
- [ ] Pacts on the GUI successfully updates timestamp. However, I get some warnings on the command line:
```bash
Verifying a pact between Pact between Inventory (1.0-SNAPSHOT) and System

  Notices:
    1) The pact at http://localhost:9292/pacts/provider/System/consumer/Inventory/pact-version/41c62f7ae02d2fe92c4d7c348bb61a58aa3a166f is being verified because it matches the following configured selection criterion: latest pact for a consumer version tagged 'open-liberty-pact'

  [from Pact Broker http://localhost:9292/pacts/provider/System/consumer/Inventory/pact-version/41c62f7ae02d2fe92c4d7c348bb61a58aa3a166f]
  Given Default directory is true
  a request to check for the default directory
    returns a response which
      has status code 200 (OK)
      has a matching body (OK)
[main] WARN au.com.dius.pact.provider.DefaultTestResultAccumulator - Not all of the 3 were verified. The following were missing:
[main] WARN au.com.dius.pact.provider.DefaultTestResultAccumulator -     a request for the version
[main] WARN au.com.dius.pact.provider.DefaultTestResultAccumulator -     a request for server name

Verifying a pact between Pact between Inventory (1.0-SNAPSHOT) and System

  Notices:
    1) The pact at http://localhost:9292/pacts/provider/System/consumer/Inventory/pact-version/41c62f7ae02d2fe92c4d7c348bb61a58aa3a166f is being verified because it matches the following configured selection criterion: latest pact for a consumer version tagged 'open-liberty-pact'

  [from Pact Broker http://localhost:9292/pacts/provider/System/consumer/Inventory/pact-version/41c62f7ae02d2fe92c4d7c348bb61a58aa3a166f]
  Given version is 1.1
  a request for the version
    returns a response which
      has status code 200 (OK)
      has a matching body (OK)
[main] WARN au.com.dius.pact.provider.DefaultTestResultAccumulator - Not all of the 3 were verified. The following were missing:
[main] WARN au.com.dius.pact.provider.DefaultTestResultAccumulator -     a request for server name

Verifying a pact between Pact between Inventory (1.0-SNAPSHOT) and System

  Notices:
    1) The pact at http://localhost:9292/pacts/provider/System/consumer/Inventory/pact-version/41c62f7ae02d2fe92c4d7c348bb61a58aa3a166f is being verified because it matches the following configured selection criterion: latest pact for a consumer version tagged 'open-liberty-pact'

  [from Pact Broker http://localhost:9292/pacts/provider/System/consumer/Inventory/pact-version/41c62f7ae02d2fe92c4d7c348bb61a58aa3a166f]
  Given wlp.server.name is defaultServer
  a request for server name
    returns a response which
      has status code 200 (OK)
      has a matching body (OK)
[main] INFO au.com.dius.pact.provider.DefaultVerificationReporter - Published verification result of 'au.com.dius.pact.core.pactbroker.TestResult$Ok@82a0f3b0' for consumer 'Consumer(name=Inventory)'

```

## Tearing down the environment

- [ ] getting `Error: No such volume: pact-broker_postgres-volume`

**Comment by meswan** [comment] 2021-01-05 15:10
For 2, as Griffin mentioned in https://github.com/OpenLiberty/draft-guide-contract-testing/issues/2#issuecomment-750374346, leaving `inventory/` to clarify which folder to be in.

3 - Didnt re hotspot `InventoryPactIT` as the file is already in focus.
4. Warnings are expected. It states which pacts were verified and which were not.
5. Couldnt reproduce docker issue.

**Comment by meswan** [comment] 2021-01-05 15:42
Tien okay with closing

**Closed as completed by meswan** 2021-01-05 15:42 UTC
